### ISSUE TITLE
FTP Uploads Feature

### ISSUE THREAD

**Issue by hbh7** [szernex/YetAnotherBackupMod#6]
Sorry, this isn't actually a real "Issue", but I wasn't sure where I should put potential feature requests.
Anyways, I turned on the FTP backup, and found that it always uploaded every single backup that ran. I was wondering if you could make it possible to set it so that only the persistent backups upload to FTP. That would save on a ton of bandwidth for my server since I have backups running every hour, and persistent backups enabled.

Since this mod is open source, I'll look into it myself to see if I can figure it out and submit a pull request, otherwise if you can add this, that'd be great. 

Thanks a bunch.

**Comment by FoxySophie** [comment]
That shouldn't be too hard to do, thanks for the suggestion

**Comment by FoxySophie** [comment]
Added a pre-release here: https://github.com/szernex/YetAnotherBackupMod/releases/tag/v1.7.10-1.0.8
Please test it and tell me if it works, I currently don't have a FTP server to test it myself.

**Comment by hbh7** [comment]
Awesome, thanks. I'll test it later today and let you know how it works.

**Comment by hbh7** [comment]
Oh, do you have a jar for it? Only see the source code there.

**Comment by FoxySophie** [comment]
Sorry about that, apparently you can't upload plain .jars anymore. The zip should be there now

**Comment by hbh7** [comment]
That's fine. Thanks. Will post results soon.

**Comment by hbh7** [comment]
Ok so after replacing my current version with this version, it still uploads both persistent and non-persistent. I made sure to set "ftpPersistentOnly=true" in the config, and ran a backup manually once to generate that persistent backup (which did upload). Then I manually ran another (it created a file in the non-persistent folder) but it still uploaded that one as well.

**Comment by FoxySophie** [comment]
Okay, I'll look into it some more then

**Comment by FoxySophie** [comment]
Well that was a brain fart on my end. Hopefully now it works as intended, still in the same release

**Comment by hbh7** [comment]
Aha ok i'll redownload it.

**Comment by hbh7** [comment]
Perfect, its functioning wonderfully now. Thanks so much!
